### ISSUE TITLE
Installation issue: invalid syntax in grizli/model.py line 3602

### ISSUE THREAD

**Issue by amn3142** [gbrammer/grizli#20]
Installing the latest version of grizli on my new machine. Running python 2.7.14, operating system CentOS 7. 

While running python setup.py install in the grizli directory, the output contains the following error: 
```

byte-compiling build/bdist.linux-x86_64/egg/grizli/model.py to model.pyc
  File "build/bdist.linux-x86_64/egg/grizli/model.py", line 3602
    def compute_model(self, *args, use_psf=True, **kwargs):
                                         ^
SyntaxError: invalid syntax
```

Changing the line to  
`    def compute_model(self, use_psf=True, *args,**kwargs):`

Seems to fix the problem.

**Comment by cdeugenio** [comment]
I had the same issue with MacOS Sierra (10.12.6), Python 2.7.14.
I downgraded from anaconda2 to miniconda2 (but I don't think this was the problem because I had the same error message also with anaconda2).
I had to copy & paste the directory "grizli" contained inside 
**/HOME/grizli/build/lib.macosx-10.6-x86_64-2.7/**  
to  
**/HOME/grizli/build/bdist.macosx-10.6-x86_64/** 
from there I had to modify the model.py as @amn3142 did.

**Comment by gbrammer** [comment]
@cdeugenio I committed a fix similar to @amn3142's suggestion.  Note that I haven't necessarily been careful with back-compatibility with python 2.7, so you might come across additional issues with the older version.

**Comment by cdeugenio** [comment]
ok ok, so do you suggest switching to python 3.5? (or 3.6?)

Thank you

**Comment by gbrammer** [comment]
Yes. I’m running 3.5.
