### ISSUE TITLE
How serious is the bug in prep.make_SEP_catalog() ?

### ISSUE THREAD

**Issue by albertfxwang** [gbrammer/grizli#49]
On Jun. 16, two bug fixes are committed (https://github.com/gbrammer/grizli/commit/90ea3762a4b140a2cc70b27c13de42aa3979800e, https://github.com/gbrammer/grizli/commit/97bd07b6f6d54d2491aad6aee418faad62425bf8) and a note was added to the change log about version 1.1 concerning this bug: "Fix bug on SEP tot_corr total correction that wasn’t using the correct pixel scale" (https://grizli.readthedocs.io/en/master/changelog.html#id7). Can I please ask how bad the effect that this bug leaves to the multiband photometric catalog and the flux level of grism spectra if their fluxes are calibrated against the broad-band photometry measured in the catalog using previous versions of grizli with this bug?

Does this commit provide the quick fix to the multiband photometric catalog derived using previous versions of grizli (https://github.com/gbrammer/grizli/commit/8822d50417791186894ad82bf5b87077f8da6956)? Or does this commit perform the combined correction of PSF+aperture to the photometric catalog in the updated versions of grizli, such that this multiband photometric catalog provides reliable color information? Thus EAZY, FAST can use it as input?

Thanks so much for your reply in advance!

**Comment by gbrammer** [comment]
Hi @albertfxwang .  Sorry I just noticed this now.  The total correction is now a correction first from an aperture flux to `auto` and then with an additional correction to total for the flux outside of the `auto` aperture for a point source based on the tabulated encircled energies in [hst_encircled_energy.fits](https://github.com/gbrammer/grizli/blob/master/grizli/data/hst_encircled_energy.fits).  The bug was that I wasn't calculating the last term correctly from image pixels to arcsec as tabulated.
